SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(REPO ${CMAKE_CURRENT_LIST_DIR})
SET(TOOLS_PREFIX ${REPO}/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-)

# @formatter:off
SET(CMAKE_C_COMPILER   ${TOOLS_PREFIX}gcc)
SET(CMAKE_CXX_COMPILER ${TOOLS_PREFIX}g++)
SET(CMAKE_LINKER       ${TOOLS_PREFIX}ld)
SET(CMAKE_ASM_COMPILER ${TOOLS_PREFIX}gcc)
SET(CMAKE_OBJCOPY      ${TOOLS_PREFIX}objcopy)
SET(CMAKE_STRIP        ${TOOLS_PREFIX}strip)
SET(CMAKE_CPP          ${TOOLS_PREFIX}cpp)
# @formatter:on

SET(CMAKE_FIND_ROOT_PATH ${REPO}/gcc-arm-none-eabi-9-2020-q2-update/lib/gcc/arm-none-eabi/9.3.1)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(STDPERIPH_LIBRARIES ${REPO}/STM32F4xx_DSP_StdPeriph_Lib_V1.8.0/Libraries)
SET(USB_STM32_LIBRARIES ${REPO}/libusb_stm32)

# @formatter:off
SET(CMSIS_INC     ${STDPERIPH_LIBRARIES}/CMSIS/Include)
SET(DEVICE_INC    ${STDPERIPH_LIBRARIES}/CMSIS/Device/ST/STM32F4xx/Include)
SET(STDPERIPH_INC ${STDPERIPH_LIBRARIES}/STM32F4xx_StdPeriph_Driver/inc)
SET(STDPERIPH_SRC ${STDPERIPH_LIBRARIES}/STM32F4xx_StdPeriph_Driver/src)
SET(LIB_CORE_INC  ${USB_STM32_LIBRARIES}/CMSIS/CMSIS/Core/Include)
SET(LIB_DEV_INC   ${USB_STM32_LIBRARIES}/CMSIS/Device/ST)
SET(LIB_USB_INC   ${USB_STM32_LIBRARIES}/inc)
SET(LIB_USB_SRC   ${USB_STM32_LIBRARIES}/src)
# @formatter:on
